apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 3scale

resources:
  - ns-3scale.yaml
  - ../../../../environments/overlays/main

patches:
  - target:
      name: 3scale-operator-group
      kind: OperatorGroup
      version: v1
      group: operators.coreos.com
    path: patch-operator-group.yaml

